// Wails v3 runtime wrapper
// This file provides type-safe wrappers around the generated Wails bindings.

// The bindings are auto-generated by `wails3 generate bindings`.
// Each service registered in main.go gets a corresponding TypeScript module.

export async function callBackend<T>(
  fn: () => Promise<T>,
  onError?: (err: Error) => void
): Promise<T | null> {
  try {
    return await fn()
  } catch (err) {
    console.error('Backend call failed:', err)
    onError?.(err as Error)
    return null
  }
}
